### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tussock** [MiMo42/MMTabBarView#37]
Hi All,

I've been putting together an app using swift and was hoping to use this toolbar - because the built in toolbars are kinda hideous. I haven't found any documentation... which has made it a little difficult, and I've not had good results yet. The demo is awesome, but is in obj-C.

As far as I can tell... I need to add a custom view, set the class to MMTabBarView and then set its tabView property pointed to an existing NSTabView. Is that required? If it is, can I hide that TabView? Also... whats the difference between partnerview and tabview properties? Your demo uses both.

It seems that I then add/remove items from the NSTabView with extra options added to the identifier property in a class (your DemoFakeModel class). Those will then get replicated into the MMTabBarView. Is that right? It doesn't seem to be working for me.

Thx for any advice you can give.

**Comment by DivineDominion** [comment]
I wonder about this, too, at the moment.

**Comment by random-developer** [comment]
I'm having similar problems with getting my MMTabBarView to work properly - connections are made correctly however it seems my issue is more one of installation.

I've dragged the MMTabBarView project into my application's project.

I've added MMTabBarView to my application's list of libraries to link against.
   - I've also added the MMTabBarView.framework to be copied into my application bundle, and I think that before I am done I'll need to change MMTabBarView's "Dynamic Library Install Name Base" to something @rpath or @executable_path based -- but as long as I'm running in Xcode this shouldn't matter yet.

Initially I'm seeing that MMTabBarView doesn't display my button tabs -- but I've figured out (by just cycling through various style settings) that if I `[_tabBarView setStyleNamed:@"Yosemite"];` then the tab bar view is rendered and it seems to work correctly.

If instead I use any styles in: Adium, Aqua, Card, LiveChat, Metal, Unified, or Safari, I get various indications that the style selection was recognized, however no buttons get rendered (and clicking where buttons should be doesn't have any effect). I can only get rendering under the Yosemite style (which is unfortunate for me since I'd like to use the Card style).
