### ISSUE TITLE
Demo app : 'Style' popup menu is disabled

### ISSUE THREAD

**Issue by barijaona** [MiMo42/MMTabBarView#76]
With demo app based on current `master`, the content of the 'Style' popup menu (in configuration drawer) is greyed out.
Observed on macOS 10.15.6, Xcode 11.6

Seems to be caused by commit 9e03810
cc @jeromectm

**Comment by jeromectm** [comment]
True; MMTabBarView's _delegate was previously weak in the declaration, but strong in the implementation. Maybe we should remove weak from the declaration, instead of adding the __weak attribute to the implementation.
However in this case, client apps should make sure that the delegate does not have a strong reference to the MMTabBarView, or there will be a retain cycle and none of them will ever be released. In my app, I will have to set the delegate to nil before closing the window containing the MMBarBarView, as the delegate is the object owning the window.

**Comment by barijaona** [comment]
Fixed by #77
